version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: monieflex_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abujesus1$
      POSTGRES_DB: MonieFlexDB
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: Abujesus1$
      DB_PORT: 5432
      DB_HOST: localhost
    depends_on:
      - db
